version: '3.4'

services:
    db:
        image: mariadb:latest
        ports:
            - '33306:3306'
        volumes:
            - ./db_data:/var/lib/mysql
            - ./mysql-init-files:/docker-entrypoint-initdb.d
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: testDB
            MYSQL_USER: developer
            MYSQL_PASSWORD: developerpassword
    blazormysqldemo.server:
        image: ${DOCKER_REGISTRY-}blazormysqldemoserver
        ports:
            - '80:80'
            - '443:443'
        build:
            context: .
            dockerfile: BlazorMysqlDemo.Server/Dockerfile
        depends_on:
            - db
        links:
            - db
