CREATE TABLE IF NOT EXISTS `testDB`.`People` (
    `Id` INT NOT NULL AUTO_INCREMENT,
    `Name` NVARCHAR(30) NOT NULL,
    `Surname` NVARCHAR(30) NOT NULL,
    PRIMARY KEY (`Id`),
    UNIQUE INDEX `Id_UNIQUE` (`Id` ASC) VISIBLE
) ENGINE = InnoDB